---
user: lukasnick
group: deployers
chdir: /var/www/algasense/current
environment: production
port: 3000
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 3
threaded: true
daemonize: true
socket: tmp/sockets/thin.sock
